version: '3'
services:
  node-app:
    container_name: node-app
    image: marv254/my-repo:nodeapp1.0
    ports:
      - 3000:3000
    # networks:
    #   - mongo-network
    
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
    - 8081:8081
    depends_on:
      - node-app
    restart: always
    # networks:
    #   - mongo-network

    volumes:
      - mongo-data:/data/db
    
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 27017:27017
    depends_on:
      - mongodb
    restart: always
    # networks:
    #   - mongo-network
volumes:
  mongo-data:
    driver: local

# networks:
#   mongo-network:
#     driver: local